#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

source "$HOME/.pass"

unalias run-help
autoload run-help
HELPDIR=/usr/local/share/zsh/help

autoload -U zmv
autoload -U zcalc

fpath=(/usr/local/share/zsh-completions $fpath)

setopt extendedglob
unsetopt CASE_GLOB

bindkey -v
bindkey '^[[1;2C' forward-word
bindkey '^[[1;2D' backward-word

source /usr/local/share/zsh/site-functions/_aws

export PATH="/usr/local/bin:/usr/local/sbin:/opt/local/sbin:$HOME/.bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin:/usr/local/share/python:/usr/local/MacGPG2/bin:/opt/X11/bin:/usr/local/opt/go/libexec/bin:$HOME/.go/bin:/usr/local/texlive/2015/bin/x86_64-darwin"

export MANPATH="/usr/local/man:$MANPATH"
export GROOVY_HOME=/usr/local/opt/groovy/libexec
export SCALA_HOME=/usr/local/opt/scala/libexec
export GOPATH="$HOME/.go"
export JAVA_HOME=`/usr/libexec/java_home`
export SSH_KEY_PATH="~/.ssh/id_rsa"
export LANG=en_US.UTF-8
export PERL_MB_OPT="--install_base \"/Users/mah/.perl5\""
export PERL_MM_OPT="INSTALL_BASE=/Users/mah/.perl5"
export HOMEBREW_GITHUB_API_TOKEN="dc32ba71c9340762ffedf31fbc628e7ef38ea15d"

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi

# Compilation flags
export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
alias zshconf="vim $HOME/.zshrc"
alias sshconf="vim $HOME/.ssh/config"
alias tarx="tar -xvf"
function tarz() {gtar -vcf "$1.tar.gz" -I pigz "$1"}
alias cam="rename -f --lower-case --camelcase"
alias cap="rename -f --upper-case"
alias decap="rename -f --lower-case"

alias stk="dirs -v"
alias ds="du -sh"
alias mmv='noglob zmv -W'
function f() { find . -iname "*$1*" ${@:2} }
function r() { grep "$1" ${@:2} -R . }
function mkcd() { mkdir -p "$@" && cd "$_"; }

# Directory bookmark handler
touch ~/.ndirs
function rbm() { sed -i "/^$1\t/d" ~/.ndirs; export $1='' }
function tbm() { hash -d _="$(pwd)" }
function bm() { rbm $1; tbm $1; echo -e "$1\t$(pwd)" >> ~/.ndirs }
function lbm() { sort ~/.ndirs }
sed -e 's/^/hash -d /' -e 's/\t/="/' -e 's/$/"/' ~/.ndirs | while read line; do eval $line; done
